### ISSUE TITLE
Files that are deleted from the GitHub Lessons repo are being left on the server

### ISSUE THREAD

**Issue by braunsb** [ianmcampbell/Arcus-Modular-Education-Support-System#10]
I found a file on the server in the ggplot2 directory called ggplot2-part-1.Rmd. I have deleted it. Its presence raises another issue that I'll start under a different thread.

_Originally posted by @braunsb in https://github.com/ianmcampbell/Arcus-Modular-Education-Support-System/issues/9#issuecomment-554033132_

The file ggplot2-part-1.Rmd was renamed swirl-ggplot2-part-1.Rmd and the new name was duly recorded in the ModuleTable.csv. When the server's lessons were updated, and the server was restarted, this file persisted, causing problems with R presenting the older file when asked for swirl-ggplot2-part-1.Rmd. 

When the lessons are updated from the Lessons repo, deletions as well as additions and other changes need to be preserved. The Lessons directory on the server should be an exact match to the Lessons repo. Is that possible? Thanks!

**Comment by braunsb** [comment]
Although I see why you would think of this as an enhancement, I think it's a bug because sometimes the wrong lesson is called and the user sees the wrong thing. it stops their progress—hence the bug label.

**Comment by ianmcampbell** [comment]
This is not a bug, because it is simply the user misunderstanding what the command does. 

`curl https://codeload.github.com/braunsb/Lessons/tar.gz/master | tar -C /srv/shiny-server/ -xz --strip=1 Lessons-master/`

This downloads the entire contents of the master branch of the Lessons repo inside a tar.gz archive and then extracts the contents to `/srv/shiny-server/`. The command does not delete any files. Thus, it is the responsibility of the user to understand how the command operates and clean up any files. 

I would accept a documentation label applied to this issue, but there is no bug present.

**Comment by ianmcampbell** [comment]
Updated the [wiki](https://github.com/ianmcampbell/Arcus-Modular-Education-Support-System/wiki/Updating-Lessons) to mention cleaning up renamed files.

**Comment by braunsb** [comment]
Actually I have a very clear understanding that the files are not being deleted. I am saying that this fact is a bug. They should be deleted from the server if they are deleted from the repo. But whatever—I am not willing to spend any more time on this. Don't fix it if you don't want to fix it. I'm not here to twist your arm, just to report what I see.

**Comment by ianmcampbell** [comment]
Transitioned to `git clone` and `get pull` method of updating with symlinks to the server directory.   Updated the [wiki](https://github.com/ianmcampbell/Arcus-Modular-Education-Support-System/wiki/Updating-Lessons) with the new methodology. Wiki section [Understanding the File Structure](https://github.com/ianmcampbell/Arcus-Modular-Education-Support-System/wiki/Understanding-File-Structure) is now out of date.
